function createfigure(XData1, YData1, XData2, YData2, XData3, YData3, XData4)
%CREATEFIGURE(XData1, YData1, XData2, YData2, XData3, YData3, XData4)
%  XDATA1:  line xdata
%  YDATA1:  line ydata
%  XDATA2:  line xdata
%  YDATA2:  line ydata
%  XDATA3:  line xdata
%  YDATA3:  line ydata
%  XDATA4:  line xdata

%  Auto-generated by MATLAB on 14-Oct-2022 15:08:01

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1);

% Create line
line(XData1,YData1,'Parent',axes1,'Marker','x','LineStyle','none',...
    'Color',[0 0 1]);

% Create line
line(XData2,YData2,'Parent',axes1,'Marker','o','LineStyle','none',...
    'Color',[0 0 1]);

% Create line
line(XData3,YData3,'Parent',axes1,'LineStyle',':');

% Create line
line(XData4,XData3,'Parent',axes1,'LineStyle',':');

% Create title
title('Poles (x) and Zeros (o)');

xaxisproperties= get(gca, 'XAxis');
xaxisproperties.TickLabelInterpreter = 'latex'; % latex for x-axis
yaxisproperties= get(gca, 'YAxis');
yaxisproperties.TickLabelInterpreter = 'latex'; % latex for x-axis

% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes1,[-2 2]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes1,[-1.5 1.5]);
box(axes1,'on');
